apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubechat-api
  namespace: staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: kubechat-staging.duckdns.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kubechat-api
                port:
                  number: 3000
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: kubechat-api
                port:
                  number: 3000
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: kubechat-api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubechat-frontend
                port:
                  number: 3000
  tls:
    - hosts:
        - kubechat-staging.duckdns.org
      secretName: kubechat-staging-tls
